### ISSUE TITLE
The keyboard shortcuts listed in the Plus Editor's help menu aren't legible. 

### ISSUE THREAD

**Issue by JaspalSuri** [SlyBouhafs/sn-theme-dracula#6]
![image](https://user-images.githubusercontent.com/44656000/101608580-ba771a00-39ba-11eb-942b-ec614d0cfd27.png)

They're visible when Futura is applied. 

Thanks again for working on this theme!

**Comment by SlyBouhafs** [comment]
Hey @JaspalSuri, thanks for reporting the issue, it should be fixed in the latest **0.0.15** release, can you confirm please?

The jsdelivr cache is pretty slow, you can use one of those two links for the install : 
https://cdn.jsdelivr.net/gh/dracula/sn-theme-dracula@master/sn-theme-dracula.json
Or : https://cdn.jsdelivr.net/gh/dracula/sn-theme-dracula@0.0.15/sn-theme-dracula.json

**Comment by JaspalSuri** [comment]
Hi @SlyBouhafs, thank you for updating it! 

Weirdly enough the theme "broke" on the desktop app and reactivating happened to fix the issue with the Plus Editor's help menu despite it being on version `0.0.13`. I'll try the latest version anyway, though. Thanks again!
